services:
  emok_db:
    image: postgres:15-alpine
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: mydb

    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
